export const CONFIG_MODULE_OPTIONS = Symbol('CONFIG_MODULE_OPTIONS');

export const DEFAULT_FALLBACK_POLL_INTERVAL_IN_SECONDS = 60;
export const MIN_FALLBACK_POLL_INTERVAL_IN_SECONDS = 1;
export const MAX_FALLBACK_POLL_INTERVAL_IN_SECONDS = 3600;
